remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-analytics
title: TLA
description: Three Letter Acronyms
favicon: assets/images/favicon.ico

jekyll_analytics:
  Plausible:
    domain: "alexroman777.github.io/tla"
    source: "https://plausible.io/js/script.js"
