---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

###############
# Rules by id #
###############
MD004: false                  # Unordered list style
MD007:
  indent: 2                   # Unordered list indentation
MD013:
  line_length: 500            # Line length limit
MD026:
  punctuation: ".,;:!。，；:"  # Trailing punctuation in header
MD029: false                  # Ordered list item prefix
MD033: false                   # Allow inline HTML
MD036: false                  # Emphasis used instead of a header

#################
# Rules by tags #
#################
blank_lines: false  # Error on blank lines