---
name: Markdown Linter

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Markdown Lint Machine
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Last Commit
        uses: github/super-linter/slim@v5
        env:
          MARKDOWN_CONFIG_FILE: .markdown-lint.yml
          VALIDATE_MARKDOWN: true
          
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}